Fix warning about implicit declaration of toupper
On a modern Linux we were getting these messages:

  c-posix.c:1848:49: warning: implicit declaration of function 'toupper'
                     note: include '<ctype.h>'
                           or provide a declaration of 'toupper'

Indeed, POSIX says this routine is provided by <ctype.h>, so including this
header should not cause any portability issues.

no-tn-check

Change-Id: I08b07d936f6e62956c12b0aa21e665aa2fb4e601